# Create specific mapping for each schema type
column_mappings = {
            "ei_tech": {
                "Event ID": "event_id",
                "Reporter Name": "reporter_name",
                "Manager Name": "manager_name",
                "branch": "branch",
                "Reported Date": "reported_date",
                "Reporter ID": "reporter_id",
                "Date Of Unsafe Event": "date_of_unsafe_event",
                "Time": "time",
                "Time of unsafe event": "time_of_unsafe_event",
                "Unsafe Event Type": "unsafe_event_type",
                "Business Details": "business_details",
                "Site Reference": "site_reference",
                "Unsafe Event location": "unsafe_event_location",
                "Product Type": "product_type",
                "Employee ID": "employee_id",
                "Employee Name": "employee_name",
                "Subcontractor Company Name": "subcontractor_company_name",
                "SubcontractorID": "subcontractor_id",
                "Subcontractor CITY": "subcontractor_city",
                "Subcontractor Name": "subcontractor_name",
                "KG Name": "kg_name",
                "Country Name": "country_name",
                "Division": "division",
                "Department": "department",
                "City": "city",
                "Sub-Area": "sub_area",
                "District": "district",
                "Zone": "zone",
                "Serious Near Miss": "serious_near_miss",
                "Unsafe Act": "unsafe_act",
                "Unsafe Act other": "unsafe_act_other",
                "Unsafe Condition": "unsafe_condition",
                "Unsafe Condition other": "unsafe_condition_other",
                "Work Stopped": "work_stopped",
                "Stop Work NOGO Violation": "stop_work_nogo_violation",
                "NOGO Violation detail": "nogo_violation_detail",
                "Stop Work Duration": "stop_work_duration",
                "Other Safety Issues": "other_safety_issues",
                "Comments/Remarks": "comments_remarks",
                "Event requires sanction": "event_requires_sanction",
                "Action Description 1": "action_description_1",
                "Action Description 2": "action_description_2",
                "Action Description 3": "action_description_3",
                "Action Description 4": "action_description_4",
                "Action Description 5": "action_description_5",
                "Image": "image",
                "Status": "status",
                "Region": "region"
            },
            "srs": {
                "Event Id": "event_id",
                "Reporter Name": "reporter_name",
                "Reported Date": "reported_date",
                "Reporter ID": "reporter_id",
                "Date Of Unsafe Event": "date_of_unsafe_event",
                "Time of unsafe event": "time_of_unsafe_event",
                "Unsafe Event Type": "unsafe_event_type",
                "Business Details": "business_details",
                "Site Reference": "site_reference",
                "Unsafe Event location": "unsafe_event_location",
                "Product Type": "product_type",
                "Employee ID": "employee_id",
                "Employee Name": "employee_name",
                "Subcontractor Company Name": "subcontractor_company_name",
                "SubcontractorID": "subcontractor_id",
                "Subcontractor CITY": "subcontractor_city",
                "Subcontractor Name": "subcontractor_name",
                "KG Name": "kg_name",
                "Country Name": "country_name",
                "Division": "division",
                "Department": "department",
                "City": "city",
                "Sub-Area": "sub_area",
                "District": "district",
                "Zone": "zone",
                "Serious Near Miss": "serious_near_miss",
                "Unsafe Act": "unsafe_act",
                "Unsafe Act other": "unsafe_act_other",
                "Unsafe Condition": "unsafe_condition",
                "Unsafe Condition other": "unsafe_condition_other",
                "Work Stopped": "work_stopped",
                "Stop Work NOGO Violation": "stop_work_nogo_violation",
                "NOGO Violation detail": "nogo_violation_detail",
                "Stop Work Duration": "stop_work_duration",
                "Other Safety Issues": "other_safety_issues",
                "Comments/Remarks": "comments_remarks",
                "Event requires sanction": "event_requires_sanction",
                "Action Description 1": "action_description_1",
                "Action Description 2": "action_description_2",
                "Action Description 3": "action_description_3",
                "Action Description 4": "action_description_4",
                "Action Description 5": "action_description_5",
                "Branch": "branch",
                "Region": "region"
            },
            "ni_tct": {
                "Reporting ID": "reporting_id",
                "Status_Key": "status_key",
                "Status": "status",
                "Location_Key": "location_key",
                "Location": "location",
                "Branch_Key": "branch_key",
                "No": "no",
                "Branch Name": "branch_name",
                "Region_Key": "region_key",
                "Region": "region",
                "Reporter SAP ID": "reporter_sap_id",
                "Reporter Name": "reporter_name",
                "Designation_Key": "designation_key",
                "Designation": "designation",
                "GL ID_Key": "gl_id_key",
                "GL ID": "gl_id",
                "PE ID_Key": "pe_id_key",
                "PE ID": "pe_id",
                "Created On": "created_on",
                "Date and Time of Unsafe Event": "date_and_time_of_unsafe_event",
                "Type Of Unsafe Event_Key": "type_of_unsafe_event_key",
                "Type Of Unsafe Event": "type_of_unsafe_event",
                "Unsafe Event Details_Key": "unsafe_event_details_key",
                "Unsafe Event Details": "unsafe_event_details",
                "Action Related to High Risk Situation_Key": "action_related_to_high_risk_situation_key",
                "Action Related to High Risk Situation": "action_related_to_high_risk_situation",
                "Business Details_Key": "business_details_key",
                "Business Details": "business_details",
                "Site Name": "site_name",
                "Site Reference_Key": "site_reference_key",
                "Site Reference": "site_reference",
                "Product Type_Key": "product_type_key",
                "Product Type": "product_type",
                "Persons Involved": "persons_involved",
                "Work Was Stopped_Key": "work_was_stopped_key",
                "Work Was Stopped": "work_was_stopped",
                "Work Stopped Hours": "work_stopped_hours",
                "No Go Violation_Key": "no_go_violation_key",
                "No Go Violation": "no_go_violation",
                "Job No": "job_no",
                "Additional Comments": "additional_comments",
                "Has Attachment": "has_attachment",
                "Attachment": "attachment"
            },
            "ni_tct_augmented": {
                # Original NI TCT columns
                "Reporting ID": "reporting_id",
                "Status_Key": "status_key",
                "Status": "status",
                "Location_Key": "location_key",
                "Location": "location",
                "Branch_Key": "branch_key",
                "No": "no",
                "Branch Name": "branch_name",
                "Region_Key": "region_key",
                "Region": "region",
                "Reporter SAP ID": "reporter_sap_id",
                "Reporter Name": "reporter_name",
                "Designation_Key": "designation_key",
                "Designation": "designation",
                "GL ID_Key": "gl_id_key",
                "GL ID": "gl_id",
                "PE ID_Key": "pe_id_key",
                "PE ID": "pe_id",
                "Created On": "created_on",
                "Date and Time of Unsafe Event": "date_and_time_of_unsafe_event",
                "Type Of Unsafe Event_Key": "type_of_unsafe_event_key",
                "Type Of Unsafe Event": "type_of_unsafe_event",
                "Unsafe Event Details_Key": "unsafe_event_details_key",
                "Unsafe Event Details": "unsafe_event_details",
                "Action Related to High Risk Situation_Key": "action_related_to_high_risk_situation_key",
                "Action Related to High Risk Situation": "action_related_to_high_risk_situation",
                "Business Details_Key": "business_details_key",
                "Business Details": "business_details",
                "Site Name": "site_name",
                "Site Reference_Key": "site_reference_key",
                "Site Reference": "site_reference",
                "Product Type_Key": "product_type_key",
                "Product Type": "product_type",
                "Persons Involved": "persons_involved",
                "Work Was Stopped_Key": "work_was_stopped_key",
                "Work Was Stopped": "work_was_stopped",
                "Work Stopped Hours": "work_stopped_hours",
                "No Go Violation_Key": "no_go_violation_key",
                "No Go Violation": "no_go_violation",
                "Job No": "job_no",
                "Additional Comments": "additional_comments",
                "Has Attachment": "has_attachment",
                "Attachment": "attachment",
                # Augmented columns - direct mapping (already have prefixes)
                "weather_weather_condition": "weather_weather_condition",
                "weather_temperature_celsius": "weather_temperature_celsius",
                "weather_humidity_percent": "weather_humidity_percent",
                "weather_weather_severity_score": "weather_weather_severity_score",
                "employee_employee_age": "employee_employee_age",
                "employee_experience_level": "employee_experience_level",
                "employee_years_of_experience": "employee_years_of_experience",
                "employee_safety_training_hours": "employee_safety_training_hours",
                "employee_last_training_date": "employee_last_training_date",
                "employee_shift_type": "employee_shift_type",
                "site_site_risk_category": "site_site_risk_category",
                "site_last_safety_audit_days": "site_last_safety_audit_days",
                "workload_workload_category": "workload_workload_category",
                "workload_team_size": "workload_team_size",
                "workload_work_duration_hours": "workload_work_duration_hours"
            }
        }
